name: py10
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-aarch64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==24.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.0
      - cattrs==24.1.2
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - chex==0.1.7
      - colorama==0.4.6
      - contourpy==1.3.1
      - coremltools==8.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dm-tree==0.1.8
      - docopt==0.6.2
      - etils==1.11.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - flax==0.10.2
      - fonttools==4.55.3
      - fsspec==2024.12.0
      - gast==0.6.0
      - google-auth==2.37.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - humanize==4.11.0
      - idna==3.10
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keras==2.15.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ncnn==1.0.20240820
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==1.23.5
      - oauthlib==3.2.2
      - onnx==1.17.0
      - opencv-python==4.10.0.84
      - openvino==2024.6.0
      - openvino-telemetry==2024.5.0
      - opt-einsum==3.4.0
      - optax==0.2.1
      - orbax-checkpoint==0.6.4
      - packaging==23.2
      - paho-mqtt==2.1.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.0.0
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - portalocker==3.0.0
      - prompt-toolkit==3.0.48
      - protobuf==4.25.5
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyaml==24.12.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rpds-py==0.22.3
      - rplcd==1.3.1
      - rsa==4.9
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - six==1.17.0
      - smbus2==0.5.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-cpu-aws==2.15.1
      - tensorflow-decision-forests==1.8.1
      - tensorflow-estimator==2.15.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflowjs==4.22.0
      - tensorstore==0.1.71
      - termcolor==2.5.0
      - tf-keras==2.15.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tinytuya==1.15.1
      - toolz==1.0.0
      - torch==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - ultralytics==8.3.52
      - ultralytics-thop==2.0.13
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.14.1
      - wurlitzer==3.1.1
      - yarg==0.1.9
      - zipp==3.21.0
